spring:
  application:
    name: userService
  datasource:
    url: jdbc:mysql://localhost:3306/planet
    username: root
    password: forest..
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 8081

sa-token:
  token-name: token
  jwt-secret-key: 5b4c7e7c-c6c7-4f7f-b7c7-c7c7c7c7c7c7
