spring:
  application:
    name: userService
  datasource:
    url: jdbc:mysql://localhost:3306/planet
    username: root
    password: forest..
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 8081
