spring:
  datasource:
    url: jdbc:mysql://localhost:3306/planet
    username: root
    password: forest..
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000

  application:
    name: generateService
  freemarker:
    template-loader-path: "D:/planet/template"
    suffix: ".ftl"
    enabled: true
server:
  port: 8082


