#resilience4j:
#  circuitbreaker:
#    instances:
#      register-health-indicator: true
#      failure-rate-threshold: 50  # 失败率阈值
#      sliding-window-size: 10     # 计算失败率的滑动窗口大小
#      wait-durationIn-open-state: 10000ms  # 打开状态的等待时间
#      permitted-number-of-callsIn-half-open-state: 5  # 半开状态允许的请求次数
#      event-consumer-bufferSize: 10
spring:
  main:
    allow-bean-definition-overriding: true

  autoconfigure:
    exclude:
      - com.kai.planet.common.config.RolesAspectAutoConfiguration
      - com.kai.planet.common.config.GlobalExceptionHandlerAutoConfiguration

  application:
    name: gatewayService
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: fileService
          uri: lb://fileService
          predicates:
            - Path=/file/**
          filters:
            - name: CircuitBreaker
              args:
                name: FileServiceFallback
                fallbackUri: forward:/file/fallback

        - id: generateService
          uri: lb://generateService
          predicates:
            - Path=/generate/**
          filters:
            - name: CircuitBreaker
              args:
                name: GenerateServiceFallback
                fallbackUri: forward:/generate/fallback

        - id: userService
          uri: lb://userService
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: UserServiceFallback
                fallbackUri: forward:/user/fallback

        - id: serverService
          uri: lb://serverService
          predicates:
            - Path=/server/**
          filters:
            - name: CustomCircuitBreakerFilterFactory
            - name: CircuitBreaker
              args:
                name: ServerServiceFallback
                fallbackUri: forward:/server/fallback

server:
  port: 8080

