hystrix:
  metrics:
    polling-interval-ms: 10000

spring:
  main:
    allow-bean-definition-overriding: true

  autoconfigure:
    exclude:
      - com.kai.planet.common.config.RolesAspectAutoConfiguration
      - com.kai.planet.common.config.GlobalExceptionHandlerAutoConfiguration

  application:
    name: gatewayService
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: fileService
          uri: lb://fileService
          predicates:
            - Path=/file/**
          filters:
            - name: CustomCircuitBreakerFilterFactory
            - name: CircuitBreaker
              args:
                name: FileServiceFallback
                fallbackUri: forward:/file/fallback

        - id: generateService
          uri: lb://generateService
          predicates:
            - Path=/generate/**
          filters:
            - name: CustomCircuitBreakerFilterFactory
            - name: CircuitBreaker
              args:
                name: GenerateServiceFallback
                fallbackUri: forward:/generate/fallback

        - id: userService
          uri: lb://userService
          predicates:
            - Path=/user/**
          filters:
            - name: CustomCircuitBreakerFilterFactory
            - name: CircuitBreaker
              args:
                name: UserServiceFallback
                fallbackUri: forward:/user/fallback

        - id: serverService
          uri: lb://serverService
          predicates:
            - Path=/server/**
          filters:
            - name: CustomCircuitBreakerFilterFactory
            - name: CircuitBreaker
              args:
                name: ServerServiceFallback
                fallbackUri: forward:/server/fallback



        - id: emailService
          uri: lb://emailService
          predicates:
            - Path=/email/**
          filters:
            - name: CustomCircuitBreakerFilterFactory
            - name: CircuitBreaker
              args:
                name: EmailServiceFallback
                fallbackUri: forward:/email/fallback

server:
  port: 8080

